image: maven:3-openjdk-17

variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version --no-transfer-progress"

cache:
  paths:
    - .m2/repository/

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test